name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install npm -g
    - run: npm install
    - run: npx nyc --reporter=lcov npm test
      env:
        CI: true
    - name: Codecov
      uses: codecov/codecov-action@v1.1.0
